name: nuitka

on: [ push, pull_request ]

jobs:
  build_linux:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Update pip
      run: python -m pip install --upgrade pip
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Install Nuitka
      run: pip install Nuitka
    - name: Package with Nuitka
      run: python3 -m nuitka --lto=yes 
          --clang 
          --include-package=PIL._tkinter_finder 
          --assume-yes-for-downloads 
          --standalone 
          --onefile 
          --linux-onefile-icon=assets/icon.png 
          VirtuVirus.py
    - name: Extract current branch name
      shell: bash
      run: ref="${GITHUB_REF#refs/heads/}" && echo "::set-output name=branch::${ref////-}"
      id: ref
    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: virtuvirus-artifacts-nuitka-linux-${{ steps.ref.outputs.branch }}
        path: |
          VirtuVirus.bin
          assets
          LICENSE
          README.md
  
  build_windows:
    runs-on: windows-latest

    steps:
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Update pip
      run: python -m pip install --upgrade pip
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Install Nuitka
      run: pip install Nuitka
    - name: Package with Nuitka
      run: python3 -m nuitka
          --lto=yes 
          --clang 
          --include-package=PIL._tkinter_finder 
          --assume-yes-for-downloads 
          --standalone 
          --onefile 
          --windows-disable-console 
          --windows-icon-from-ico=assets/icon.ico 
          VirtuVirus.py
    - name: Extract current branch name
      shell: bash
      run: ref="${GITHUB_REF#refs/heads/}" && echo "::set-output name=branch::${ref////-}"
      id: ref
    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: virtuvirus-artifacts-nuitka-windows-${{ steps.ref.outputs.branch }}
        path: |
          assets
          VirtuVirus.exe
          LICENSE
          README.md
