name: pyinstaller

on: [ push, pull_request ]

jobs:
  build_linux:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Install PyInstaller
      run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
    - name: Package with PyInstaller
      run: pyinstaller --onefile VirtuVirus.py
    - name: Post Packaging Step
      run: mv dist/VirtuVirus VirtuVirus
    - name: Extract current branch name
      shell: bash
      run: ref="${GITHUB_REF#refs/heads/}" && echo "::set-output name=branch::${ref////-}"
      id: ref
    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: virtuvirus-artifacts-linux-${{ steps.ref.outputs.branch }}
        path: |
          VirtuVirus
          LICENSE
  build_windows:
    runs-on: windows-latest

    steps:
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Install PyInstaller
      run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
    - name: Package with PyInstaller
      run: pyinstaller --onefile -F --add-data "assets/icon.ico;assets/icon.ico" --icon="assets/icon.ico" VirtuVirus.py
    - name: Post Packaging Step
      shell: bash
      run: mv dist/VirtuVirus.exe VirtuVirus.exe
    - name: Extract current branch name
      shell: bash
      run: ref="${GITHUB_REF#refs/heads/}" && echo "::set-output name=branch::${ref////-}"
      id: ref
    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: virtuvirus-artifacts-windows-${{ steps.ref.outputs.branch }}
        path: |
          VirtuVirus.exe
          LICENSE